export const CART_ADD_ITEM = ' CART_ADD_ITEM';
export const CART_REMOVE_ITEM = ' CART_REMOVE_ITEM';

export const UPDATE_SHIPPING_ADDRESS = 'UPDATE_SHIPPING_ADDRESS';

export const UPDATE_PAYMENT_METHOD = 'UPDATE_PAYMENT_METHOD';

export const CART_RESET_ITEMS = 'CART_RESET_ITEMS';
